# Generated by Django 4.2.1 on 2023-05-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_coursecategory_coursesection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name_plural": "3. Courses"},
        ),
        migrations.AlterModelOptions(
            name="coursecategory",
            options={"verbose_name_plural": "2. Course Categories"},
        ),
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name_plural": "1. Faculties"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name_plural": "4. Students"},
        ),
    ]
